Lib/fontmake/font_project.py

Instead, just maintain lists of the scale and offset factors and apply
them in order during the decompilation of a specific component. This
is more straightforward when you consider some complex cases (e.g. an
inverted component which itself has a component with an offset).
Should fix https://github.com/googlei18n/fontmake/issues/17 (cc @brawer)

Don't compound scale/offsets during decomposition

---

Lib/fontmake/font_project.py

Uses fontTools.subset, which also drops glyph names unless the flag
"Don't use Production Names" is set.
Part of https://github.com/googlei18n/fontmake/issues/20

Add option to subset based on Glyphs flags

---

Lib/fontmake/font_project.py

glyphs2ufo now outputs kerning rules with ufo3-style group names (as of https://github.com/googlei18n/glyphs2ufo/commit/d2b1a23b3af16e3a04bb52d038f5cd44654514f0), so there's no need for a special kern writer class.

Don't use special kern writer for Glyphs

---

Lib/fontmake/font_project.py

This uses the new glyph names from the output binary to define a
glyph subset. It also uses a period as the script suffix delimiter
since that's what ufo2ft expects.

Account for renaming in subset step

---

requirements.txt

This reverts commit 402e8f8ae59eae52ced388bed71e5c80fbe8c430.
Followup to typesupply/fontMath#25.

Revert "Add missing robofab dependency"

---

README.md

Using `sudo` with `pip` is not good. The Linux or OSX's system python is part of the operating system and should not be modified by the users via external package managers like `pip`.
Users should be recommended to use pip's `--user` option, which installs in the user's site-packages, or better use `virtualenv`, which does not require admin privileges and provides isolation from the dependency hell.

README.md: don't recommend using `sudo` to install fontmake and deps

---

requirements.txt

This corrects designspace path naming and improves kerning conflict
warning messages.
Fixes https://github.com/googlei18n/fontmake/issues/73
Part of https://github.com/googlei18n/fontmake/issues/80 and closes https://github.com/googlei18n/fontmake/issues/79

Update glyphsLib to latest upstream

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

Some font source may already have removed overlap, or one may not want to remove overlaps. booleanOperations cannot yet remove overlap for quadratic curves: https://github.com/typemytype/booleanOperations/issues/26.

Add option to keep overlaps

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

This can be used along with --keep-overlaps, in case the source already has the right contours.

Add option to keep direction since default reverses contour direction

---

requirements.txt

This should fix parsing of Glyphs source with un-escaped unicode
characters.

Update glyphsLib requirement

---

Lib/fontmake/font_project.py
requirements.txt

The current ufo2ft has a new `convertCubics=True` argument  which conflicts with fontmake, as the latter already calls `cu2qu.font[s]_to_quadratic` before passing the font to ufo2ft.
So fontmake needs to set that to False.

avoid converting the curves twice with latest ufo2ft

---

Lib/fontmake/font_project.py

If one passes `--keep-overalap` option, then `booleanOperations` should not be required by fontmake.

font_project: move booleanOperations import inside 'remove_overalap' method

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

`save_otfs` method has a `subset` keyword argument which defaults to `True`, without a command line option to disable it.
The fonttools Subsetter is called on the generated font, even if the input UFO does not have any `com.schriftgestaltung.Keep Glyphs` key in the `lib.plist`, nor any of the .glif libs have `com.schriftgestaltung.Glyphs.Export` set to False.
This PR set the default value of 'subset' argument to `None`, and adds two command line options `--subset` and `--no-subset`.
`None` means run the subsetter only if the "Keep Glyphs" list is present in the lib.plist.

do not always run the fonttools subsetter

---

Lib/fontmake/font_project.py

fixes #118
There are still py23 issues with mutatorMath, but @moyogo promised he has patch for that.

[py23] open glyphs source as UTF-8; import unicode_literals; write bytes to tempfile

---

dev_requirements.txt

It could be used as a shorthand for checking if anything breaks when some dependency gets updated, before modifying the actual "requirements.txt" file (which must keep pinned-down versions).

dev_requirements.txt: install all dependencies from HEAD

---

Lib/fontmake/font_project.py
requirements.txt

on Windows we need to close the temporary file, before we can re-open it by the name... Which basically makes the whole use of NamedTemporaryFile almost pointless...
See https://bugs.python.org/issue14243
Anyway, this fixes it for now.
If we find we need to do this often, we can wrap the `try... finally` in a custom @contextmanager that does the cleanup on exit.

Windows: fix "IOError: [Errno 13] Permission denied" when re-opening named temporary file

---

Lib/fontmake/__main__.py

The `--autohint` option uses `nargs=?` which allows to specify the option without argument (or with 1 argument), defaulting to `None`.
However, in `save_otfs`, the ttfautohint subprocess is called only if the `autohint` keyword argument is not None.
I would expect that calling fontmake with `-a` would run ttfautohint using the latter's default options, but at the moment it is simply ignored.
Either we make `-a` option require an argument and raise if one is not provided (which is the argparse default behavior, without `nargs=?`) or we use `const` to use a constant empty string when the option is provided without argument following it, which is what I do here: 
https://docs.python.org/3/library/argparse.html#const

[ttfautohint] run with default options if --autohint is specified without argument

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

This PR depends on https://github.com/googlei18n/ufo2ft/pull/61
If that's merged, the fontmake default behavior would remain the same as the current one: i.e., always run compreffor if a CFF table is present.
But In addition, fontmake could gently skip running compreffor when the latter is not installed (it's still a bit tricky to compile compreffor on Windows, but I'm working on providing pre-compiled wheels for that).
On the other hand, if the '-s' ('--subroutinize') option is explicitly provided, then ufo2ft raises ImportError when compreffor is not installed.
Finally, when the '-S' ('--no-subroutinize') option is provided, fontmake tells ufo2ft to skip compreffor altogether, whether it's installed or not.
Note that on makeotf subroutinization is optional, not default.
I'm ok with …

add --subroutinize/--no-subroutinize options

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

This controls the the `max_err_em` value that is passed on to `cu2qu.fonts_to_quadratic`.
So it should be a float number measured as a ratio of abstract font units divided by the UPEM.
The default value is the same as the current cu2qu default (which our designers think is a bit too generous): `0.0025`, or 2.5 units on a grid of 1000 UPEM.

add --conversion-error option for cu2qu

---

Lib/fontmake/__main__.py

Should resolve https://github.com/googlei18n/fontmake/issues/126

Only use single-letter short options (no -mi)

---

dev_requirements.txt
requirements.txt

As of version 0.5.1, booleanOperations is published on [PyPI](
https://pypi.org/project/booleanOperations) so one can `pip install booleanOperations`.

requirements.txt: update booleanOperations

---

requirements.txt

using pre-compiled wheels from compreffor's Github Releases page.
@marekjez86 regarding https://github.com/googlei18n/fontmake/issues/150, I was able to build NotoSansSymbols2-Regular on my local machine using the latest fontmake and compreffor.

requirements.txt: update compreffor==0.3.0

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

This allows the user to specify whether they want to see the build status messages or not via a --verbosity flag.
It has the side effect, however, of printing info from dependencies. In the case of MutatorMath, which otherwise runs silently for a long time, this isn't necessarily a bad thing. Though in some cases (e.g. fontTools' subsetter) the info messages can be a bit noisy.
We probably want to do something similar for glyphsLib, ufo2ft, and cu2qu.
@marekjez86: this should radically change the format of fontmake console output, but may allow us to build LGC fonts on Travis. (At least, it shouldn't time out due to MutatorMath silence.  The overall process may still take too long.)

Use logging module

---

Lib/fontmake/font_project.py
requirements.txt

Sometimes booleanOperations may fail because the input contours are invalid for clipping (e.g. see https://github.com/googlei18n/fontmake/issues/161)
With https://github.com/typemytype/booleanOperations/pull/37, we can catch a `BooleanOperationsError`, and let users know where to find the invalid path, so they can fix it.
Also, we can use `booleanOperations.union` function directly, instead of instantiating a `BooleanOperationManager` instance, as the `union` method is static anyway.
This PR depends on the above PR being merged first.

font_project.py: log the font/glyph names when booleanOperations fail

---

.gitignore
Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

Add `--use-kern-writer` and `--use-mark-writer` options that allow me to override the `ufo2ft` built-in `KernFeatureWriter` and `MarkFeatureWriter` classes with my custom ones. 
I made one such class in [`feaLab`](https://github.com/twardoch/feaLab) which basically does nothing. This allows me to use `fontmake` to build [`VotoSerifGX-OFL`](https://github.com/twardoch/varfonts-ofl/tree/master/VotoSerifGX-OFL) where `fontmake` currently fails because it cannot merge OTL tables.

Add --use-kern-writer and --use-mark-writer options

---

.gitignore
Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

hey Adam @twardoch 
I reviewed your PR #200 and added a few commits on top of it.
- I renamed the options to `--kern-writer-module` and `--mark-writer-module`; I think it's better as they take a module name argument, while `--use-...` seems to imply a boolean value.
- the argument parser passes the class objects themselves rather than the module names; this also gives the chance to raise a parser.error when the module can't be imported or does not contain a class with the expected name. I think it's more reasonable to raise here, instead of just log a warning.
- I kept the grouping of the arguments, and only made cosmetic changes here and there.
Please take a look, thanks.

follow up on PR #200

---

Lib/fontmake/font_project.py

I was a bit confused by the `glyph_filter: lambda g: g` in this commit
https://github.com/googlei18n/fontmake/commit/a858bff08f1ac5847c80dad291be81508835125a#diff-77503f3639ebd287f468b3d480600aa9R178
until I realised that a Defcon Glyph object returns True with `bool(glyph)` if it contains any contours, or False otherwise.
I presume this works because it implements some of the built-in list methods (`__len__`, `__getitem__`, etc); however I don't see `__bool__` or `__nonzero__` anywhere in:
https://github.com/typesupply/defcon/blob/master/Lib/defcon/objects/glyph.py
Anyway, a test like `if not glyph: continue` looks a bit obscure to me when used on glyph objects, which do work like lists but are not quite lists.
I think it's clearer if we instead check the `len(glyph)`.
Also, I think that …

clarify that only 'mixed' glyphs are decomposed for TTFs

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
test/test_arguments.py

This is a follow-up on PR #266.
The `-i/--interpolate` option is used to make instance UFOs with MutatorMath and shouldn't be used along with `-o variable` output; `fontTools.varLib` expects interpolatable _master_ TTFs (plus designspace), not _instances_.
Therefore, for the `build_variable_font` function, the argument `is_instance` or `interpolatable` don't make any sense and I removed them.
I also changed the default folder where variable fonts gets generated to "variable_ttf".
In the previous PR #266, @zjusbo used "master_ttf_variable", but I believe neither the 'master' nor 'instance' attributes qualify really well a variable font, which is... both!
Finally, since when generating a variable font we require a designspace file (or a glyphs file from which we generate a designspace …

make interpolate/variable mutually exclusive; save VF to "variable_ttf"

---

Lib/fontmake/font_project.py
requirements.txt
setup.py

ufo2ft v0.4.0 changed the names of some modules, classes and arguments.
I adapted fontmake to use the current names.
Full changelog:
https://github.com/googlei18n/ufo2ft/releases/tag/v0.4.0

update fontmake to use the latest ufo2ft v0.4.0 API

---

.travis.yml

The pip version installed by default on the Travis python is too old and does not support installing from binary 'manylinux1' wheels.
Upgrading pip should speed up the CI builds, as we can install pyclipper and compreffor from the pre-compiled wheel packages.

[travis] update pip to install from precompiled manylinux1 wheels

---

.travis.yml
test/InterpolateLayoutTest/InterpolateLayoutTest 0 GPOS.txt
test/InterpolateLayoutTest/InterpolateLayoutTest 1000 GPOS.txt
test/InterpolateLayoutTest/InterpolateLayoutTest GDEF.txt
test/InterpolateLayoutTest/InterpolateLayoutTest GSUB.txt
test/InterpolateLayoutTest/InterpolateLayoutTest.glyphs
test/InterpolateLayoutTest/InterpolateLayoutTest.plist
test/run.sh

The InterpolateLayoutTest.glyphs file includes glyphs 'V' and 'a' from Adobe Source Sans Pro.
The MTI GPOS source files specify a simple kern pair between these two glyphs which vary between the Light and Bold masters.
For now, I simply call fontmake from the `run.sh` shell script and check the exit code, like the other existing tests currently do.
The commands used are the same as the ones used in the `build_plist` function of `noto-source/util.sh`.
Fontmake is called once to make the master_ttf using the mti sources, then again in order to interpolate the instance_ttf, using varLib to interpolate the GPOS.
Later on, we shall port everything to pure python unittest-style tests, and assert that results match expected values.
But for now this will at least catch issues like …

add basic tests for --mti-souce and --interpolate-binary-layout

---

Lib/fontmake/font_project.py

After this change, the master UFOs are self-contained in the sense
that no external files are needed to compile them, even in workflows
that use Monotype (MTI) feature files instead of Adobe feature files.
We still need to change ufo2ft so it actually recognizes these newly
embedded files, but this can be done independently.
https://github.com/googlei18n/fontmake/issues/289

Copy MTI feature files into master UFOs

---

Lib/fontmake/font_project.py
requirements.txt
setup.py

Instead of injecting the Monotype feature files late into the
pipeline, we now embed them into UFO files so that the UFOs are fully
self-contained. This change also cleans up the way how the data
gets embedded into the UFO; instead of changing files underneath
defcon, fontmake now calls the defcon data APIs.
The handling of Monotype feature files was added to ufo2ft in
version 0.4.3, so fontmake now requires that version.
https://github.com/googlei18n/fontmake/issues/289

Clean up workflow for Monotype feature files

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
requirements.txt
setup.py

- Fix AttributeError with new ufo2ft  FeatureCompiler (v0.5.0)
- make --use-afdko and --mti-source options mutually exclusive
- remove unused arguments and update some related docstrings

fix FDKFeatureCompiler and --mti-source

---

Lib/fontmake/font_project.py

On Windows, running the command `makeotf` with subprocess.check_output fails with `FileNotFoundError: [WinError 2] The system cannot find the file specified`.

Use makeotf.cmd instead of makeotf on win32

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

As discussed here:
https://github.com/googlei18n/ufo2ft/issues/192#issuecomment-355019434
by default we will now pass `roundGeometry=False` to MutatorMath, so the generated UFOs will have un-rounded float geometry. A new `--round-instances` option (replacing the [unreleased] `--no-round`) can be used to force integer geometry to the interpolated instance UFOs.
I called it `--round-instances` instead of simply `--round` to make it clear that this has nothing to do with the rounding that is specific to the output format (which occurs anyway but later on in the pipeline), but is only effective for interpolation of the intermediate instance sources.
The required integer rounding will be applied for us automatically by the fonttools pens (for coordinates), or by ufo2ft compiler for other …

rename --no-round to --round-instances (positive), False by default

---

Lib/fontmake/__main__.py
Lib/fontmake/errors.py
Lib/fontmake/font_project.py
Lib/fontmake/ttfautohint.py
requirements.txt
setup.py

The two options are mutually exclusive.
`--output-path` can only be used when the output is a single file: e.g. when the input is a single UFO, or when only one instance was selected for export, or the source contains only one master, or the output format is a variable font.
The `--output-dir` option can be used with any binary output. The folder is created if it doesn't exist.
Finally, the `--interpolate-binary-layout` option now takes an optional parameter to customize the location of the binary masters used with `varLib.interpolate_layout` (e19f00f).
Fixes https://github.com/googlei18n/fontmake/issues/333 and https://github.com/googlei18n/fontmake/issues/396

add --output-path and --output-dir options

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

In https://github.com/googlei18n/fontmake/pull/410#issuecomment-377329203, I added --master-dir and --instance-dir options to control where the glyphsLib-generated UFOs are created, and override the hardcoded "master_ufo"/"instance_ufo" directories.
Sometimes one may only be interested in running fontmake end-to-end from .glyphs sources to binary TTF or OTFs (or variable TTF), and thus the master_ufo and instance_ufo folders that are created in the current working directory are just unwanted leftovers.
This PR allows to pass to `--master-dir` or `--instance-dir` a special string `{tmp}`, which means create a temporary directory and use that, then clean it up automatically after finished.
I chose `{tmp}` because is short and it's unlikely that one wants to use it as the real name for an …

optionally save master/instance ufos to temporary directory

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

decomposing glyphs, removing overlaps, converting curves to quadratic can be done by appropriate ufo2ft preprocessor filters, fontmake only needs to pass the right options to the top-level compile functions.
Note that this was already implemented in the current stable ufo2ft 1.1.0 released in december last year, we just didn't update fontmake to make use of them.
Also, adds support for `cff_round_tolerance`. In ufo2ft the argument is called simply `roundTolerance` but here we need to distinguish it from the other one called `round_instances`.

update to use current ufo2ft API

---

Lib/fontmake/font_project.py

The glyph names of UFO anf OT binary need to match up for the export flag testing to work. The .notdef glyph must be handled specially because it is usually the first glyph in the OT, but might not be present or in the first glyph slot in the UFO.
https://github.com/googlei18n/fontmake/issues/443
Now for some tests.

subset_otf_from_ufo: Handle .notdef glyph

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
test/DesignspaceTestSharedFeatures/DesignspaceTest-Light.ufo/fontinfo.plist
test/DesignspaceTestSharedFeatures/DesignspaceTest-Light.ufo/glyphs/contents.plist
test/DesignspaceTestSharedFeatures/DesignspaceTest-Light.ufo/glyphs/layerinfo.plist
test/DesignspaceTestSharedFeatures/DesignspaceTest-Light.ufo/layercontents.plist
test/DesignspaceTestSharedFeatures/DesignspaceTest-Light.ufo/metainfo.plist
test/DesignspaceTestSharedFeatures/DesignspaceTest-Regular.ufo/features.fea
test/DesignspaceTestSharedFeatures/DesignspaceTest-Regular.ufo/fontinfo.plist
test/DesignspaceTestSharedFeatures/DesignspaceTest-Regular.ufo/glyphs/contents.plist
test/DesignspaceTestSharedFeatures/DesignspaceTest-Regular.ufo/glyphs/layerinfo.plist
test/DesignspaceTestSharedFeatures/DesignspaceTest-Regular.ufo/layercontents.plist
test/DesignspaceTestSharedFeatures/DesignspaceTest-Regular.ufo/metainfo.plist
test/DesignspaceTestSharedFeatures/DesignspaceTestSharedFeatures.designspace
test/run.sh

I want to tackle #359.
Rather than changing the paths (complicated because you have to rewrite the AST recursively), here I just expand the feature file to every instance. Optional because Adobe's workflow apparently is to manage this manually.

Optionally expand feature files to instance UFOs

---

requirements.txt
setup.py

We need 3.37.1 for the MVAR generation fix.

Bump requirements for fontTools

---

README.rst

The repo has moved to a new org, and the Travis CI badge now shows "unknown",
even though the tests themselves are passing. This change restores the Travis CI
green build status, and also updates the repo paths for cloning and releases.

Update org from `googlei18n` to `googlefonts`

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
requirements.txt
setup.py
test/test_arguments.py

NOTE: this PR requires https://github.com/googlefonts/ufo2ft/pull/332 to be merged (and released) first.

use ufo2ft.compileVariable{TTF,CFF2}

---

Lib/fontmake/font_project.py

I just made an unexpected discovery..
It turns out that, when a designspace document defines axes `map` elements... (e.g. these are Noto Sans' axes)
```xml
<axis tag="wght" name="Weight" minimum="100" maximum="900" default="400">
<map input="100" output="26"/>
<map input="200" output="39"/>
<map input="300" output="58"/>
<map input="400" output="90"/>
<map input="500" output="108"/>
<map input="600" output="128"/>
<map input="700" output="151"/>
<map input="800" output="169"/>
<map input="900" output="190"/>
</axis>
<axis tag="wdth" name="Width" minimum="62.500000" maximum="100" default="100">
<map input="62.500000" output="70"/>
<map input="75" output="79"/>
<map input="87.500000" output="89"/>
<map input="100" output="100"/>
</axis>
```
... MutatorMath will "bend" the masters and …

work around MutatorMath "warping" sources/instances locations

---

Lib/fontmake/instantiator.py
tests/test_instantiator.py

Closes #574.
I overlooked that ufoProcessor does the same. Several attributes are actually specific to instances and should not be blindly inherited from the default font.
The ignore list is different from ufoProcessor. We additionally ignore:
- openTypeNameUniqueID
- openTypeNameWWSFamilyName
- openTypeNameWWSSubfamilyName
- openTypeOS2Panose
We copy over:
- familyName
- woffMajorVersion
- woffMetadataCopyright
- woffMetadataCredits
- woffMetadataDescription
- woffMetadataExtensions
- woffMetadataLicense
- woffMetadataLicensee
- woffMetadataTrademark
- woffMetadataVendor
- woffMinorVersion
This implies that the styleName attribute is now implicitly required. Not specifying it in the Designspace means it will not be set in the instance.

Copy font info attributes from default font to instance selectively

---

Lib/fontmake/instantiator.py
tests/data/DesignspaceTest/MyFont-Light.ufo/groups.plist
tests/test_instantiator.py

ufoProcessor does the same: https://github.com/LettError/ufoProcessor/blob/c23240dc20922fed84b458632041310dea526c2d/Lib/ufoProcessor/__init__.py#L688-L694.
Kerning groups are taken care of by MathKerning.
This should have no user-visible impact but is more a "doing it a bit more correctly" type of change.

Copy only non-kerning groups explicitly

---

requirements.txt
setup.py

When fontmath is already installed, upgrading fontmake should also upgrade it to the minimum requirement.
The required version of MutatorMath could require fontMath>=0.5.0 instead but it actually doesn’t use `setRoundIntegerFunction`.

fontMath.mathFunctions.setRoundIntegerFunction only in fontMath>=0.5.0

---

Lib/fontmake/font_project.py
tests/data/TestSubset.glyphs
tests/test_main.py

when an instance has "Keep Glyphs" custom parameter, fontmake runs the fonttools subsetter on the OTF just built and prunes all glyphs not present in that list. Since the postscript glyph names in OTF may have been renamed using final production uni-names, fontmake needs to match the original glyph names in UFO and the ones in the OTF by their glyph index.
Now that glyphsLib/ufo2ft support the `public.skipExportGlyphs` option, and fontmake enables this feature by default  (unless `--no-write-skipexportglyphs` option is passed), this means that the built OTF may contain less glyphs than the original UFO (glyphs in public.skipExportGlyphs are not exported) and so we hit as AssertionError as the two glyphOrder have different lengths.
This fixes the problem by only considering the actually …

fix interaction with skipExportGlyphs and post-build subsetting feature

---

Lib/fontmake/instantiator.py
tests/data/SwapGlyphNames/A.ufo/glyphs/a.glif
tests/data/SwapGlyphNames/A.ufo/glyphs/a.swap.glif
tests/test_instantiator.py

Glyph.clear() destroys all anchors (and pen protocol does not 'draw' them).
`fontmake.instantiator` needs to also swap the glyph anchors when applying the DesignSpace conditional substitution rules, just like it does for the contours and components.
Otherwise, the swapped glyphs will lose all their anchors and get no mark/mkmk features...
**NOTE**: If you used fontmake to generate fonts that contain "bracket" glyphs or a DesignSpace document with rvrn-style conditional substitution rules, and these glyphs contain any anchors which were supposed to be used to generate mark or mkmk feature, I strongly recommend that you re-generate your fonts using the new fontmake and glyphsLib (which we are going to release shortly after this is merged).
Apologies, we should have caught this earlier.
Many …

instantiator: when applying DS rules, must also swap anchors

---

Lib/fontmake/__main__.py
Lib/fontmake/errors.py
Lib/fontmake/font_project.py
Lib/fontmake/instantiator.py
Lib/fontmake/ttfautohint.py

Produce better error messages

---

Lib/fontmake/font_project.py
Lib/fontmake/instantiator.py

This will indicate to the user what to look for in case of explosions.
Also includes a small band-aid to avoid adding a path to a FontmakeError source_trail if something down the call stack added it already. This avoids duplicate source indicators depending on which code path is taken.

Catch and reraise varLib erros in instantiator setup

---

Lib/fontmake/instantiator.py
tests/test_instantiator.py

The intention (and varLib's behavior probably) is to only use the default source's groups for kerning group information. Before this PR, we accidentally had Instantiator use the groups associated with each source individually. fontMath makes a union of them, which is fine if all groups are the same, but leads to problems otherwise.
ufoProcessor suffers from the same problems and assumes groups are identical: https://github.com/LettError/ufoProcessor/blob/88323a4/Lib/ufoProcessor/__init__.py#L392-L393

Ensure only the default groups are used in interpolation

---

Lib/fontmake/instantiator.py
tests/test_instantiator.py

The default font determines which glyphs are interpolated, because the math behind varLib and MutatorMath needs the default font as a point of reference for all data to be interpolated.

Use default glyphs for interpolation

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
requirements.txt
setup.py
tests/test_main.py

Uses the latest ufo2ft with cffsubr support to allow subroutinizing CFF2 tables.
Also adds a new 'otf-cff2' output format, for non-variable CFF2 fonts

support subroutinizing with cffsubr; add otf-cff2 static output

---

Lib/fontmake/instantiator.py
tests/data/DesignspaceRuleOrder/MyFont.designspace
tests/data/DesignspaceRuleOrder/MyFont_Black.ufo/fontinfo.plist
tests/data/DesignspaceRuleOrder/MyFont_Black.ufo/glyphs/Q_.alt.glif
tests/data/DesignspaceRuleOrder/MyFont_Black.ufo/glyphs/Q_.glif
tests/data/DesignspaceRuleOrder/MyFont_Black.ufo/glyphs/Q_.ss01.alt.glif
tests/data/DesignspaceRuleOrder/MyFont_Black.ufo/glyphs/Q_.ss01.glif
tests/data/DesignspaceRuleOrder/MyFont_Black.ufo/glyphs/contents.plist
tests/data/DesignspaceRuleOrder/MyFont_Black.ufo/layercontents.plist
tests/data/DesignspaceRuleOrder/MyFont_Black.ufo/lib.plist
tests/data/DesignspaceRuleOrder/MyFont_Black.ufo/metainfo.plist
tests/data/DesignspaceRuleOrder/MyFont_Hair.ufo/fontinfo.plist
tests/data/DesignspaceRuleOrder/MyFont_Hair.ufo/glyphs/Q_.alt.glif
tests/data/DesignspaceRuleOrder/MyFont_Hair.ufo/glyphs/Q_.glif
tests/data/DesignspaceRuleOrder/MyFont_Hair.ufo/glyphs/Q_.ss01.alt.glif
tests/data/DesignspaceRuleOrder/MyFont_Hair.ufo/glyphs/Q_.ss01.glif
tests/data/DesignspaceRuleOrder/MyFont_Hair.ufo/glyphs/contents.plist
tests/data/DesignspaceRuleOrder/MyFont_Hair.ufo/layercontents.plist
tests/data/DesignspaceRuleOrder/MyFont_Hair.ufo/lib.plist
tests/data/DesignspaceRuleOrder/MyFont_Hair.ufo/metainfo.plist
tests/test_instantiator.py

Hello, I pushed here a test that reproduces a bug with the instanciator when several designspace rules touch the same glyphs. I wrote a test designspace and [a description of what should happen in the docstring of the test](https://github.com/googlefonts/fontmake/pull/689/files#diff-60bba4bf61f2028edf91b4e75a5728f2R276-R288).
Instead of the expected result, there are two problems I would like to address in this PR:
* with the rules of the designspace provided as a test case, the output is wrong
* the output is also random, which can make it right sometimes by luck
The misbehaved code is below:
https://github.com/googlefonts/fontmake/blob/f07b1932768efdee8f15a4a9179d1c2d181ceb8a/Lib/fontmake/instantiator.py#L376-L383
Here is what I get if I put a breakpoint after line 380:
```
$ fontmake …
```

Fix two problems: non-determinism and incorrect rule application in instanciator

---

Lib/fontmake/__main__.py

I compiled [Noto Nastaliq Urdu](https://github.com/googlefonts/noto-source/tree/master/src/NotoNastaliqUrdu) today and was confused by the help string for the fontmake `--mti-source` option.  This build uses the [Monotype OpenType Layout Source](https://monotype.github.io/OpenType_Table_Source/otl_source.html) format with a combination of multiple `*.txt` files and a single `*.plist` file for GSUB, GPOS, and GDEF table definitions.  The fontmake help menu indicates that the command line argument is the "Path to mtiLib .txt feature definitions".  This PR clarifies that the plist file path is the required command line argument.

Update --mti-source help string

---

.github/workflows/ci.yml
README.rst
build_pyz.sh
setup.py
tox.ini

3.10 is out next week, while 3.6 reaches end of life by the end of this year.
It's time to require 3.7 or greater, so we can finally use built-in dataclasses and more.

drop Python 3.6, require >= 3.7

---

.github/workflows/ci.yml
Lib/fontmake/font_project.py
requirements.txt
setup.py

This tells glyphsLib to create enough UFO for building binary fonts and discard any unneeded data.
This requires glyphsLib 6.0.0 or later.

Use glyphsLib minimal builds

---

Lib/fontmake/ttfautohint.py
requirements.txt
setup.py

The ttfautohint-py python wrapper does not come with a `ttfautohint` script, to avoid shadowing the original ttfautohint (c++) executable. But one can still call it from the command line or as a subprocess with `python -m ttfautohint`. This PR does that instead of importing ttfautohint and using its Python API, to avoid make too broad changes and continue to support the standalone ttfautohint command.
Fixes https://github.com/googlefonts/fontmake/issues/562
Required for #850  /cc @yanone

add support for ttfautohint-py

---

Lib/fontmake/font_project.py
tests/data/AutohintingTest/Padyakke.glyphs
tests/test_main.py

I wouldn't know how to write a test for this, so unless you insist, I'm skipping

Chain autohinting parameters from Glyphs source to fontmake

---

Lib/fontmake/compatibility.py

If there's more than 6 fonts, only show the font count.
Before
```
Fonts had differing anchors in glyph A:
* RobotoFlex GRAD-200 had "bottom, ogonek"
* RobotoFlex GRAD150, RobotoFlex opsz144, RobotoFlex opsz8, 
RobotoFlex wdth151, RobotoFlex wdth25, RobotoFlex wght100, 
RobotoFlex wght 1000, RobotoFlex Regular had "bottom, ogonek, top"
```
After
```
Fonts had differing anchors in glyph A:
* RobotoFlex GRAD-200 had "bottom, ogonek"
* 8 fonts had "bottom, ogonek, top"
```
Fixes #854

CompatibilityChecker: make large error messages more concise

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
tests/test_main.py

Fixes https://github.com/googlefonts/fontmake/issues/866

Add option to disable ttfautohint even if source has 'TTFAutohint options'

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

Add support for UFOZ as input format when no -u flag is used

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

Referring to both ufoLib and defcon, add ` structure={"package", "zip"}` to `save_ufo_as` function and appropriate calls.
Fixes #887 .

Add options and save to .ufoz

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
tests/test_compatibility.py

The compatibility checker is really nice for reporting errors but it's actually pretty heavy to run on fonts where we already have built it before and know things are OK. This saves a few seconds.

Allow disabling the compatibility checker

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
tests/test_main.py

logging configuration is global, does not belong to a specific `fontmake.FontProject` instance, so it should only be done inside `main()`. This PR deprecates the `verbose` and `timing` parameters to FontProject constructor and moves the logging configuration to the CLI module (`fontmake.__main__`).
The old parameter continue to work but a deprecation warning is issued (category is actually `UserWarning` as `DeprecationWarning` proper are usually muted -- just to shout it out more louder)
It also enables logging configuration for a logger named "ufo2ft.timer" (which reports timing info inside ufo2ft) which doesn't exist yet but will soon (https://github.com/googlefonts/ufo2ft/pull/641)
This and fontmake's own timing logger are controlled by the fontmake `--timing` flag, independently from …

clean up logging configuration

---

Lib/fontmake/instantiator.py
requirements.txt
setup.py
tests/data/InstantiatorStrictMathGlyph/SquareOne.ufo/fontinfo.plist
tests/data/InstantiatorStrictMathGlyph/SquareOne.ufo/glyphs/contents.plist
tests/data/InstantiatorStrictMathGlyph/SquareOne.ufo/glyphs/layerinfo.plist
tests/data/InstantiatorStrictMathGlyph/SquareOne.ufo/glyphs/test.glif
tests/data/InstantiatorStrictMathGlyph/SquareOne.ufo/layercontents.plist
tests/data/InstantiatorStrictMathGlyph/SquareOne.ufo/lib.plist
tests/data/InstantiatorStrictMathGlyph/SquareOne.ufo/metainfo.plist
tests/data/InstantiatorStrictMathGlyph/SquareTwo.ufo/fontinfo.plist
tests/data/InstantiatorStrictMathGlyph/SquareTwo.ufo/glyphs/contents.plist
tests/data/InstantiatorStrictMathGlyph/SquareTwo.ufo/glyphs/layerinfo.plist
tests/data/InstantiatorStrictMathGlyph/SquareTwo.ufo/glyphs/test.glif
tests/data/InstantiatorStrictMathGlyph/SquareTwo.ufo/layercontents.plist
tests/data/InstantiatorStrictMathGlyph/SquareTwo.ufo/lib.plist
tests/data/InstantiatorStrictMathGlyph/SquareTwo.ufo/metainfo.plist
tests/data/InstantiatorStrictMathGlyph/StrictMathGlyph.designspace
tests/test_instantiator.py

This fixes #961, and makes instantiator.py as strict as varLib when interpolating.
Depends on https://github.com/robotools/fontMath/pull/305, though, as fontMath doesn't properly propagate its "strict" flag down to copies.
So this PR should probably also update its fontMath version dependency, once a new fontMath is out.

Use MathGlyph's "strict" flag

---

Lib/fontmake/__main__.py
Lib/fontmake/errors.py
Lib/fontmake/font_project.py
Lib/fontmake/instantiator.py
tests/data/MutatorSans/MutatorSans-non-default-layer.designspace
tests/test_instantiator.py

This PR adds the ability to build from non-default layers. If the default designspace source is set to a non-default layer, then its glyphset is used as reference for all the other sources—glyphs that are not on the layer are discarded. I believe this should also address issue #603

Instantiator support for non-default layer sources

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
requirements.txt
setup.py
tests/test_main.py

The designspace reading/writing capabilities of MutatorMath are no longer supported, and have been replaced my [ufoProcessor](https://github.com/LettError/ufoProcessor).
This PR drops support for generating static instance UFOs using MutatorMath. Users who wish to continue using MutatorMath-only anisotropic locations or extrapolation are advised to use ufoProcessor separately to generate their instance UFOs, and then use fontmake to compile them to TTF/OTF.
Fixes #834

remove MutatorMath integration

---

Lib/fontmake/font_project.py
tests/test_main.py

Now that we dropped MutatorMath support (which required to read sources from disk, #1019) we can directly build VFs or static instances from in-memory designspace + UFO objects as returned from glyphsLib or generated by fontmake.instantiator. This should considerably speed up build time as we can avoid spending time serializing UFOs.
A few places that assumed things were read from/written to the filesystem had to be tweaked, however the normal behaviour is unchanged.
Except that now, in order to actually save the designspace or UFOs, one has to explicitly include 'ufo' in the list of output formats in `-o` option.
And when the *only* output is `-o ufo`, then one can also use the `--output-dir` option (works for either masters or instances) or even the `--output-path` option when selecting …

Don't save master/instance ufos by default unless -o ufo is requested

---

Lib/fontmake/font_project.py

run_from_glyphs(): ufo_structure default to package

---

setup.py

I was working with Pydigger API  project that tracks different projects from PYPI that show various stats including incomplete packaging info, fontmake popped up and I decided to update the information.

Added Names of Authors and contributors in setup.py

---

Lib/fontmake/compatibility.py
tests/test_compatibility.py

This PR:
* adds checking for the compatibility of GPOS contexts between contextual anchors (which can cause very confusing merge errors as entire lookups end up not aligning).
* improves the display of compatibility error messages
Before:
```
ERROR:fontmake.compatibility:Fonts had differing point type in glyph D, contour 0, point 9:
ERROR:fontmake.compatibility: * Incompatible Sans Regular had curve
ERROR:fontmake.compatibility: * Incompatible Sans Bold had line
ERROR:fontmake.compatibility:Fonts had differing point type in glyph D, contour 0, point 10:
ERROR:fontmake.compatibility: * Incompatible Sans Regular had None
ERROR:fontmake.compatibility: * Incompatible Sans Bold had line
ERROR:fontmake.compatibility:Fonts had differing point type in glyph D, contour 0, point 11: …
```

Improve compatibility checker

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
requirements.txt
setup.py

this is meant to work with https://github.com/googlefonts/ufo2ft/pull/635
should hold merging until new ufo2ft gets released

add option to disable ufo2ft variable FEA, restore varLib merging of OTL tables

---

requirements.txt
tests/test_main.py

Most notably, to pick up https://github.com/fonttools/fonttools/pull/3688
Also https://github.com/googlefonts/glyphsLib/pull/1048

Update to FontTools 4.55 and glyphsLib 6.9.5
