googlefonts/fontmake

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
setup.py

Adds a few things:
- command line tool "fontmake" (to close #5)
- option to build from UFO sources (to close #2)
- option to build using the AFDKO to compile features (to close #6)
cc @brawer @behdad @davelab6

API updates

---

Lib/fontmake/font_project.py

I'm thinking this is not very important, but I had it locally and decided to push it. I could take it or leave it as far as merging.

Minor API change

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

MutatorMath input

---

Lib/fontmake/font_project.py
requirements.txt

This is mostly to use defcon throughout the toolchain, but also includes a little cleanup.

Use defcon

---

.travis.yml
Lib/fontmake/font_project.py
requirements.txt

Also hopefully serves as a test for CI testing

Reverse contours

---

README.md

It looks similar to [fonttools](https://github.com/behdad/fonttools/).

Show current build status on fontmake project page

---

Lib/fontmake/font_project.py

If a component is flipped upside-down or mirrored sideways, its
contour direction will be reversed. Correct the contours for
components to which this applies.
Part of https://github.com/googlei18n/fontmake/issues/22

Correct component directions when decomposing

---

requirements.txt

Fixes https://github.com/googlei18n/fontmake/issues/83

Update glyphsLib to latest upstream

---

Lib/fontmake/font_project.py

Same as https://github.com/googlei18n/ufo2ft/pull/39/commits/cddb01d595fbef64ff9009fa3fcb95948da715c1

public.glyphOrder may contain glyphs that are not in the font

---

requirements.txt

Fixes https://github.com/googlei18n/fontmake/issues/40, https://github.com/googlei18n/fontmake/issues/82

Update ufo2ft requirement

---

requirements.txt

Resolves https://github.com/googlei18n/fontmake/issues/90

Update fonttools requirement

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

Add option to use production names or not as alternative to default which uses production name unless disabled with glyph.lib's com.schriftgestaltung.Don't use Production Names

Add option for production names

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

This should allow building masters and instances with `-i -mi`. All outputs will be put into instance output directories. Resolves https://github.com/googlei18n/fontmake/issues/107
r? @khaledhosny

Add option to treat masters as instances

---

requirements.txt

Since glyphsLib has been updated since I submitted my first pr, I've set it to the latest.

requirements.txt: update glyphsLib to commit 0630c67

---

Lib/fontmake/font_project.py

Get kwargs in method signatures, not with pop()

---

Lib/fontmake/__main__.py

See https://github.com/googlei18n/fontmake/pull/127#issuecomment-238381511

fontmake.main: restore --subroutinize True by default

---

.travis.yml
dev_requirements.txt
requirements.txt

Update requirements to latest HEAD

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
requirements.txt

Depends on https://github.com/googlei18n/glyphsLib/pull/75

Variable fonts

---

Lib/fontmake/__main__.py

IMO this is more readable. Of course that's very subjective so I'm happy to close this if there are strong feelings the other way.

Change format of argument parsing code

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
requirements.txt

Option to interpolate layout from master binaries

---

requirements.txt

download the wheel from PyPI, so installation is quicker.

update requirements.txt to download packages from PyPI

---

Lib/fontmake/font_project.py

Before, fontmake would assume master UFOs were found in a master_ufo
directory. Now hopefully they can be just about anywhere.

More robust building of variable font

---

Lib/fontmake/font_project.py

Part of https://github.com/googlei18n/fontmake/issues/169

Suppress info messages from fontTools.subset

---

requirements.txt

This will get rid of missing unicode messages when interpolating.

Update MutatorMath requirement

---

Lib/fontmake/font_project.py

Biggest change is that we decompose any glyph with contours when compiling TTFs. Also contains minor logging and doc additions.

Decompose in TTF build

---

Lib/fontmake/font_project.py

https://github.com/googlei18n/noto-fonts/issues/830

change -GX to -VF in variable font output file name. #830

---

setup.py

- fonttools from 3.9.0 to 3.9.1
- glyphsLib from 1.5.2 to 1.6.0
- ufo2ft from 0.4.0 to 0.4.1
- MutatorMath from 2.0.2 to 2.0.3
- defcon from 0.2.4 to 0.3.1
- booleanOperations from 0.6.4 to 0.7.0

[setup.py] update minimum requirements to latest versions

---

Lib/fontmake/font_project.py

Use font.path if present to generate output path

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py

See https://github.com/googlei18n/glyphsLib/pull/220

Add --no-round argument to use designspace roundGeometry=False

---

Lib/fontmake/__main__.py
Lib/fontmake/errors.py
Lib/fontmake/font_project.py
requirements.txt
setup.py
test/AvarDesignspaceTest/AvarDesignspaceTest.designspace

add a new `-I/--instance-name` command line option that can be used to select a specific instance (or instances) to generate from a designspace file.
Also uses the new `glyphsLib.to_designpace` API, and depends on https://github.com/googlei18n/glyphsLib/pull/339 for applying instance data on the selected instances.
will add some tests soon

Allow to build selected instances

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
requirements.txt
setup.py
test/AvarDesignspaceTest/AvarDesignspaceTest.designspace
test/test_arguments.py

WIP: Sparse layers and (experimental) CFF2 support

---

Lib/fontmake/__main__.py
test/run.sh

Should fix https://github.com/googlei18n/fontmake/issues/515.

Prevent expand_features_to_instances from reaching run_from_ufos

---

.pre-commit-config.yaml
Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
README.rst
build_pyz.sh
pyproject.toml
setup.cfg
setup.py

https://github.com/googlefonts/fontmake/issues/560

Make Python 3 only

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
requirements.txt
setup.py
tests/test_main.py

For dumping the content of auto-generated OT features to aid debugging

Add --debug-feature-file option 

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
requirements.txt
setup.py

Requires googlefonts/ufo2ft#438

Add flatten components option

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
setup.py
tests/test_main.py

This adds a `--filter` argument.
Depends on https://github.com/googlefonts/ufo2ft/pull/466 and https://github.com/googlefonts/ufo2ft/pull/479.

Add --filter argument

---

setup.py

See https://github.com/pypa/pip/issues/7953

[setup.py] Work around pip bug with "pip install -e ."

---

Lib/fontmake/font_project.py
tests/data/TestSubset2.glyphs
tests/test_main.py

See https://github.com/googlefonts/glyphsLib/issues/735
- Implement Remove Glyphs custom feature
- Tests for Remove Glyphs

Implement Remove Glyphs custom feature

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
requirements.txt
setup.py

requires ~~not-yet-released~~ ufo2ft 2.32 and fonttools 4.40
https://github.com/googlefonts/ufo2ft/pull/753
https://github.com/fonttools/fonttools/pull/3147

add option to --drop-implied-oncurves

---

Lib/fontmake/__main__.py
Lib/fontmake/font_project.py
tests/data/GlyphData.xml
tests/data/GlyphsUnitTestSans.glyphs
tests/test_main.py

To pass custom GlyphData XML files to glyphsLib.
Fixes #245.

Add --glyph-data option
